### ISSUE TITLE
Sentry common errors

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-api#136]
@olehkorkh-planeks these are the most common issues, could you take a look? Thanks.

- [ ] TypeError Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7ff74f4c1d10>.
    - [Link to issue](https://opencap.sentry.io/issues/4443417349/events/3f594d194bab4628bdc5c63a430a0e6b/) 
    - Should be fixed w/ #140
- [ ] OSError write error
    - [Link to issue](https://opencap.sentry.io/issues/4237254939/events/9d6357c531b848efbe1ad75d57a4d6b7/) 
- [ ] Session matching query does not exist.
    - [Link to issue](https://opencap.sentry.io/issues/4619683656/events/5db90bbeebcc4305b24bff8268b06ec6/)
    - Should be fixed w/ #143
- [ ] (Different one) TypeError %i format: a number is required, not str
    - [Link to issue](https://opencap.sentry.io/issues/4444985513/events/2148fb848a834f1b803de772f48da9c5/)
    -  Should be fixed w/ #140
- [ ] (Different one) TypeError %i format: a number is required, not str
    - [Link to issue](https://opencap.sentry.io/issues/4648878804/events/4b56527f99364d1d95ee459bb2e91352/)
    -  Should be fixed w/ #140
- [ ] ValidationError ['“undefined” is not a valid UUID.']
    - [Link to issue](https://opencap.sentry.io/issues/4637080285/events/4751f1304ad742fe96c4f71bb540196c/)
    - Should be fixed w/ #143

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse 
> (Different one) TypeError %i format: a number is required, not str
[Link to issue](https://opencap.sentry.io/issues/4444985513/events/2148fb848a834f1b803de772f48da9c5/)
(Different one) TypeError %i format: a number is required, not str
[Link to issue](https://opencap.sentry.io/issues/4648878804/events/4b56527f99364d1d95ee459bb2e91352/)

These issues have to be already fixed in `dev` branch, because I already had similar errors but with other messages.
Here you can see the difference between `main` and `dev` branches for `django.po` file.
https://share.cleanshot.com/z1jypZS71WdVYRznz66D

As you see, the `main` version has incorrect format string syntax. The `dev` branch has fixed version of the `.po` file and corresponded `.mo` file as well.

**Comment by antoinefalisse** [comment]
@olehkorkh-planeks @suhlrich @AlbertoCasasOrtiz 

We tried to understand this issue with @AlbertoCasasOrtiz:

> TypeError Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7ff74f4c1d10>.
[Link to issue](https://opencap.sentry.io/issues/4443417349/events/3f594d194bab4628bdc5c63a430a0e6b/)

Before what we merged yesterday, it was possible for non logged in users to hit new session same setup from a public session not belonging to them (see [this issue](https://github.com/stanfordnmbl/opencap-viewer/issues/205)), which would call [this endpoint ](https://github.com/stanfordnmbl/opencap-viewer/blob/main/src/store/data.js#L304). And this would create [this problem](https://opencap.sentry.io/issues/4619683656/events/5db90bbeebcc4305b24bff8268b06ec6/?project=4505279706562560). Bottom line: this should be fixed. So let's no add your fix for now but keep it mind.

I will merge the other one.
