### ISSUE TITLE
move download to a lambda function or celerey worker

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-api#38]
People are reporting unreliable download with large files, and we recently introduced "download data for subject" function which will trigger large downloads. This isn't really something that should be happening on the API server, and I suspect it may be the cause of it going down. Moving video upload from the server will help. It'd be nice to also move the downloadAndZip session to a lambda function. thoughts @AlbertoCasasOrtiz, @antoinefalisse? Maybe for the next Planeks round (Oleh could def. do it, not sure about new developer).

**Comment by antoinefalisse** [comment]
Great idea, please go ahead and create a detailed issue that we can assign to Planeks.

**Comment by AlbertoCasasOrtiz** [comment]
This sounds good. This may solve all of our problems related to download.

**Comment by suhlrich** [comment]
What are the other download problems aside from big sessions failing?

On Apr 21, 2023, at 2:19 PM, Alberto ***@***.***> wrote:

﻿

This sounds good. This may solve all of our problems related to download.

**Comment by AlbertoCasasOrtiz** [comment]
This one here: https://github.com/stanfordnmbl/opencap-api/issues/6. Since it is an old one, I just tested it and it is still an issue.

**Comment by olehkorkh-planeks** [comment]
I think that we can implement that feature differently. Now we have a Celery worker that we can use for running long tasks in the background. For the current moment, we use it only for periodical cleaning of the DB from trashed objects. But it is a good tool for running such code, like preparing the data for download.

We can fix the current implementation by replacing using API endpoints with ORM and running the data preparation asynchronously in the background. It should be more reliable than working with API because we will not use the web load balancer in that case and will not be affected by any timeouts. This is the reason also why I think that using Lambda is not the best choice for this task.

When a user chooses the “Download” link, we will show a popup like “Please wait, we’re archiving the data” with an animated spinner. At that moment, the background task will be added to the Celery queue for preparing the file. Then, the .zip file will be uploaded to the S3 and the new signed URL will be generated. During that time the downloading pop-up waits when URL will be ready and show the “Download” button, instead of spinner, for downloading the file.

In case user will close the tab during the process, .zip file will be prepared without issues. We can also add separate page in the app with a list of generated files. So, user can open it and download new file. Or, download some previously prepared files if it needed. We can delete old files to clean the space.

Let me know your thoughts.

**Comment by suhlrich** [comment]
This is good @olehkorkh-planeks. Let's also have an option to "download again" in case updates to the data or analyses have been made since they last downloaded.

**Comment by antoinefalisse** [comment]
Closed with #81
