### ISSUE TITLE
Sessions created as child of another session lose calibration trial if the parent is removed.

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [stanfordnmbl/opencap-api#45]
Right now, you can remove every session. This is colliding with the `New Session, Same Setup` functionality, since it is creating a tree of sessions in which the root is the one having the calibration trial that every child is using. If any session in the tree is removed, this means none of its children will have a way of locating the calibration trial. And what is worse, if the root is removed, none of the children has a calibration trial.

Possible solutions by Scott:

> Some solutions:
> 
> - instead of deleting full sessions, leave the static trial. This will delete it from the users view, but not break the new session same setup feature
> - See if a session is ever recorded as a "newsessionSameSetup" session, and prevent session deletion if so.

> I think the idea would be to change the function of the \sessions\session_id\remove_permanently endpoint. That way all the scheduling stuff doesn't change

**Comment by antoinefalisse** [comment]
@suhlrich and @AlbertoCasasOrtiz how about adding something (eg, a list of child session IDs) to the parent session when a child session is created. Then we could something like:
- When deleting a session that we know is a child session (has pointer to parent session ID for calibration), we also delete the "something" in the parent session
- Only allow deleting a session if is not a parent session, ie if the "something" does not exist.

**Comment by suhlrich** [comment]
something is if 'startNewSession" is in metadata

![image](https://github.com/stanfordnmbl/opencap-api/assets/43877159/b9b8c8b7-6cac-4d81-add9-c16c7449296e)

Not being able to delete a session because it was a parent session may annoy ppl who really want to delete their data. Alternatively:

`if 'startNewSession' in session.meta:
delete all trials but calibration. #this will no longer show up in trial list
else
delete session`

**Comment by suhlrich** [comment]
Desired implementation:

When deleting a session:

if 'startNewSession' in session.meta:
delete all trials but calibration. #this will no longer show up in trial list
else
delete session

**Comment by olehkorkh-planeks** [comment]
@suhlrich As I see, `startNewSession` has to be list because there is no any blocker for creating multiple child sessions for the same one. Now, as it is implemented in `new_subject` endpoint view, the backend just overrides the old id with new one. I'll improve it as well.

**Comment by olehkorkh-planeks** [comment]
Here is a PR https://github.com/stanfordnmbl/opencap-api/pull/127

**Comment by suhlrich** [comment]
Thanks for the PR @olehkorkh-planeks. We actually changed how we'd like to implement this. Whenever a session is deleted, instead of deleting the entire session instance, we'd like to delete all trial instances within a session that are not named 'calibration'

This will solve both the problem in this issue, and we want to be able to keep track of how many sessions people collect, even if they delete their data.

**Comment by olehkorkh-planeks** [comment]
@suhlrich Hi, I prepared the fix - https://github.com/stanfordnmbl/opencap-api/pull/164/files

**Comment by AlbertoCasasOrtiz** [comment]
Solved in #164 and merged in #239.
